// Copyright 2022 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package utils

import (
	"fmt"
	"testing"

	"github.com/pkg/errors"
	"github.com/stretchr/testify/assert"
)

func TestJoinUrl(t *testing.T) {
	testCases := []struct {
		baseURL     string
		relativeURL string
		expected    string
		error       error
	}{

		{"", "/", "", errors.New("base url is empty")},
		{"", "", "", errors.New("base url is empty")},
		{"", "/test/path", "", errors.New("base url is empty")},
		{"/", "/", "/", nil},
		{"/", "", "/", nil},
		{"127.0.0.1", "", "127.0.0.1", nil},

		// ip address tests with port

		{"127.0.0.1:5001/tanzu-plugins/", "/test/path/", "127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"127.0.0.1:5001/tanzu-plugins", "/test/path/", "127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"127.0.0.1:5001/tanzu-plugins", "test/path/", "127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"127.0.0.1:5001/tanzu-plugins/", "test/path/", "127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"127.0.0.1:5001/tanzu-plugins", "test/path", "127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"127.0.0.1:5001/tanzu-plugins/", "/test/path", "127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"127.0.0.1:5001/tanzu-plugins/", "test/path", "127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"127.0.0.1:5001/tanzu-plugins", "/test/path", "127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"127.0.0.1:5001/tanzu-plugins", "", "127.0.0.1:5001/tanzu-plugins", nil},
		{"127.0.0.1:5001/tanzu-plugins/", "", "127.0.0.1:5001/tanzu-plugins", nil},
		{"127.0.0.1:5001/tanzu-plugins/", "/", "127.0.0.1:5001/tanzu-plugins/", nil},

		{"http://127.0.0.1:5001/tanzu-plugins/", "/test/path/", "http://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1:5001/tanzu-plugins", "/test/path/", "http://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1:5001/tanzu-plugins", "test/path/", "http://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1:5001/tanzu-plugins/", "test/path/", "http://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1:5001/tanzu-plugins", "test/path", "http://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1:5001/tanzu-plugins/", "/test/path", "http://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1:5001/tanzu-plugins/", "test/path", "http://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1:5001/tanzu-plugins", "/test/path", "http://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1:5001/tanzu-plugins", "", "http://127.0.0.1:5001/tanzu-plugins", nil},
		{"http://127.0.0.1:5001/tanzu-plugins/", "", "http://127.0.0.1:5001/tanzu-plugins", nil},
		{"http://127.0.0.1:5001/tanzu-plugins/", "/", "http://127.0.0.1:5001/tanzu-plugins/", nil},

		{"https://127.0.0.1:5001/tanzu-plugins/", "/test/path/", "https://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1:5001/tanzu-plugins", "/test/path/", "https://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1:5001/tanzu-plugins", "test/path/", "https://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1:5001/tanzu-plugins/", "test/path/", "https://127.0.0.1:5001/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1:5001/tanzu-plugins", "test/path", "https://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1:5001/tanzu-plugins/", "/test/path", "https://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1:5001/tanzu-plugins/", "test/path", "https://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1:5001/tanzu-plugins", "/test/path", "https://127.0.0.1:5001/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1:5001/tanzu-plugins", "", "https://127.0.0.1:5001/tanzu-plugins", nil},
		{"https://127.0.0.1:5001/tanzu-plugins/", "", "https://127.0.0.1:5001/tanzu-plugins", nil},
		{"https://127.0.0.1:5001/tanzu-plugins/", "/", "https://127.0.0.1:5001/tanzu-plugins/", nil},

		{"127.0.0.1:5001/", "/test/path/", "127.0.0.1:5001/test/path/", nil},
		{"127.0.0.1:5001", "/test/path/", "127.0.0.1:5001/test/path/", nil},
		{"127.0.0.1:5001", "test/path/", "127.0.0.1:5001/test/path/", nil},
		{"127.0.0.1:5001/", "test/path/", "127.0.0.1:5001/test/path/", nil},
		{"127.0.0.1:5001", "test/path", "127.0.0.1:5001/test/path", nil},
		{"127.0.0.1:5001/", "/test/path", "127.0.0.1:5001/test/path", nil},
		{"127.0.0.1:5001/", "test/path", "127.0.0.1:5001/test/path", nil},
		{"127.0.0.1:5001", "/test/path", "127.0.0.1:5001/test/path", nil},
		{"127.0.0.1:5001", "", "127.0.0.1:5001", nil},
		{"127.0.0.1:5001/", "", "127.0.0.1:5001/", nil},
		{"127.0.0.1:5001/", "/", "127.0.0.1:5001/", nil},

		{"http://127.0.0.1:5001/", "/test/path/", "http://127.0.0.1:5001/test/path/", nil},
		{"http://127.0.0.1:5001", "/test/path/", "http://127.0.0.1:5001/test/path/", nil},
		{"http://127.0.0.1:5001", "test/path/", "http://127.0.0.1:5001/test/path/", nil},
		{"http://127.0.0.1:5001/", "test/path/", "http://127.0.0.1:5001/test/path/", nil},
		{"http://127.0.0.1:5001", "test/path", "http://127.0.0.1:5001/test/path", nil},
		{"http://127.0.0.1:5001/", "/test/path", "http://127.0.0.1:5001/test/path", nil},
		{"http://127.0.0.1:5001/", "test/path", "http://127.0.0.1:5001/test/path", nil},
		{"http://127.0.0.1:5001", "/test/path", "http://127.0.0.1:5001/test/path", nil},
		{"http://127.0.0.1:5001", "", "http://127.0.0.1:5001", nil},
		{"http://127.0.0.1:5001/", "", "http://127.0.0.1:5001/", nil},
		{"http://127.0.0.1:5001/", "/", "http://127.0.0.1:5001/", nil},

		{"https://127.0.0.1:5001/", "/test/path/", "https://127.0.0.1:5001/test/path/", nil},
		{"https://127.0.0.1:5001", "/test/path/", "https://127.0.0.1:5001/test/path/", nil},
		{"https://127.0.0.1:5001", "test/path/", "https://127.0.0.1:5001/test/path/", nil},
		{"https://127.0.0.1:5001/", "test/path/", "https://127.0.0.1:5001/test/path/", nil},
		{"https://127.0.0.1:5001/", "test/path", "https://127.0.0.1:5001/test/path", nil},
		{"https://127.0.0.1:5001/", "/test/path", "https://127.0.0.1:5001/test/path", nil},
		{"https://127.0.0.1:5001/", "test/path", "https://127.0.0.1:5001/test/path", nil},
		{"https://127.0.0.1:5001", "/test/path", "https://127.0.0.1:5001/test/path", nil},
		{"https://127.0.0.1:5001", "", "https://127.0.0.1:5001", nil},
		{"https://127.0.0.1:5001/", "", "https://127.0.0.1:5001/", nil},
		{"https://127.0.0.1:5001/", "/", "https://127.0.0.1:5001/", nil},

		// ip address tests without port

		{"127.0.0.1/tanzu-plugins/", "/test/path/", "127.0.0.1/tanzu-plugins/test/path/", nil},
		{"127.0.0.1/tanzu-plugins", "/test/path/", "127.0.0.1/tanzu-plugins/test/path/", nil},
		{"127.0.0.1/tanzu-plugins", "test/path/", "127.0.0.1/tanzu-plugins/test/path/", nil},
		{"127.0.0.1/tanzu-plugins/", "test/path/", "127.0.0.1/tanzu-plugins/test/path/", nil},
		{"127.0.0.1/tanzu-plugins", "test/path", "127.0.0.1/tanzu-plugins/test/path", nil},
		{"127.0.0.1/tanzu-plugins/", "/test/path", "127.0.0.1/tanzu-plugins/test/path", nil},
		{"127.0.0.1/tanzu-plugins/", "test/path", "127.0.0.1/tanzu-plugins/test/path", nil},
		{"127.0.0.1/tanzu-plugins", "/test/path", "127.0.0.1/tanzu-plugins/test/path", nil},
		{"127.0.0.1/tanzu-plugins", "", "127.0.0.1/tanzu-plugins", nil},
		{"127.0.0.1/tanzu-plugins/", "", "127.0.0.1/tanzu-plugins", nil},
		{"127.0.0.1/tanzu-plugins/", "/", "127.0.0.1/tanzu-plugins/", nil},

		{"http://127.0.0.1/tanzu-plugins/", "/test/path/", "http://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1/tanzu-plugins", "/test/path/", "http://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1/tanzu-plugins", "test/path/", "http://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1/tanzu-plugins/", "test/path/", "http://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"http://127.0.0.1/tanzu-plugins", "test/path", "http://127.0.0.1/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1/tanzu-plugins/", "/test/path", "http://127.0.0.1/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1/tanzu-plugins/", "test/path", "http://127.0.0.1/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1/tanzu-plugins", "/test/path", "http://127.0.0.1/tanzu-plugins/test/path", nil},
		{"http://127.0.0.1/tanzu-plugins", "", "http://127.0.0.1/tanzu-plugins", nil},
		{"http://127.0.0.1/tanzu-plugins/", "", "http://127.0.0.1/tanzu-plugins", nil},
		{"http://127.0.0.1/tanzu-plugins/", "/", "http://127.0.0.1/tanzu-plugins/", nil},

		{"https://127.0.0.1/tanzu-plugins/", "/test/path/", "https://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1/tanzu-plugins", "/test/path/", "https://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1/tanzu-plugins", "test/path/", "https://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1/tanzu-plugins/", "test/path/", "https://127.0.0.1/tanzu-plugins/test/path/", nil},
		{"https://127.0.0.1/tanzu-plugins", "test/path", "https://127.0.0.1/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1/tanzu-plugins/", "/test/path", "https://127.0.0.1/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1/tanzu-plugins/", "test/path", "https://127.0.0.1/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1/tanzu-plugins", "/test/path", "https://127.0.0.1/tanzu-plugins/test/path", nil},
		{"https://127.0.0.1/tanzu-plugins", "", "https://127.0.0.1/tanzu-plugins", nil},
		{"https://127.0.0.1/tanzu-plugins/", "", "https://127.0.0.1/tanzu-plugins", nil},
		{"https://127.0.0.1/tanzu-plugins/", "/", "https://127.0.0.1/tanzu-plugins/", nil},

		{"127.0.0.1/", "/test/path/", "127.0.0.1/test/path/", nil},
		{"127.0.0.1", "/test/path/", "127.0.0.1/test/path/", nil},
		{"127.0.0.1", "test/path/", "127.0.0.1/test/path/", nil},
		{"127.0.0.1/", "test/path/", "127.0.0.1/test/path/", nil},
		{"127.0.0.1", "test/path", "127.0.0.1/test/path", nil},
		{"127.0.0.1/", "/test/path", "127.0.0.1/test/path", nil},
		{"127.0.0.1/", "test/path", "127.0.0.1/test/path", nil},
		{"127.0.0.1", "/test/path", "127.0.0.1/test/path", nil},
		{"127.0.0.1", "", "127.0.0.1", nil},
		{"127.0.0.1/", "", "127.0.0.1/", nil},
		{"127.0.0.1/", "/", "127.0.0.1/", nil},

		{"http://127.0.0.1/", "/test/path/", "http://127.0.0.1/test/path/", nil},
		{"http://127.0.0.1", "/test/path/", "http://127.0.0.1/test/path/", nil},
		{"http://127.0.0.1", "test/path/", "http://127.0.0.1/test/path/", nil},
		{"http://127.0.0.1/", "test/path/", "http://127.0.0.1/test/path/", nil},
		{"http://127.0.0.1", "test/path", "http://127.0.0.1/test/path", nil},
		{"http://127.0.0.1/", "/test/path", "http://127.0.0.1/test/path", nil},
		{"http://127.0.0.1/", "test/path", "http://127.0.0.1/test/path", nil},
		{"http://127.0.0.1", "/test/path", "http://127.0.0.1/test/path", nil},
		{"http://127.0.0.1", "", "http://127.0.0.1", nil},
		{"http://127.0.0.1/", "", "http://127.0.0.1/", nil},
		{"http://127.0.0.1/", "/", "http://127.0.0.1/", nil},

		{"https://127.0.0.1/", "/test/path/", "https://127.0.0.1/test/path/", nil},
		{"https://127.0.0.1", "/test/path/", "https://127.0.0.1/test/path/", nil},
		{"https://127.0.0.1", "test/path/", "https://127.0.0.1/test/path/", nil},
		{"https://127.0.0.1/", "test/path/", "https://127.0.0.1/test/path/", nil},
		{"https://127.0.0.1/", "test/path", "https://127.0.0.1/test/path", nil},
		{"https://127.0.0.1/", "/test/path", "https://127.0.0.1/test/path", nil},
		{"https://127.0.0.1/", "test/path", "https://127.0.0.1/test/path", nil},
		{"https://127.0.0.1", "/test/path", "https://127.0.0.1/test/path", nil},
		{"https://127.0.0.1", "", "https://127.0.0.1", nil},
		{"https://127.0.0.1/", "", "https://127.0.0.1/", nil},
		{"https://127.0.0.1/", "/", "https://127.0.0.1/", nil},

		// localhost tests with port

		{"localhost:5001/tanzu-plugins/", "/test/path/", "localhost:5001/tanzu-plugins/test/path/", nil},
		{"localhost:5001/tanzu-plugins", "/test/path/", "localhost:5001/tanzu-plugins/test/path/", nil},
		{"localhost:5001/tanzu-plugins", "test/path/", "localhost:5001/tanzu-plugins/test/path/", nil},
		{"localhost:5001/tanzu-plugins/", "test/path/", "localhost:5001/tanzu-plugins/test/path/", nil},
		{"localhost:5001/tanzu-plugins", "test/path", "localhost:5001/tanzu-plugins/test/path", nil},
		{"localhost:5001/tanzu-plugins/", "/test/path", "localhost:5001/tanzu-plugins/test/path", nil},
		{"localhost:5001/tanzu-plugins/", "test/path", "localhost:5001/tanzu-plugins/test/path", nil},
		{"localhost:5001/tanzu-plugins", "/test/path", "localhost:5001/tanzu-plugins/test/path", nil},
		{"localhost:5001/tanzu-plugins", "", "localhost:5001/tanzu-plugins", nil},
		{"localhost:5001/tanzu-plugins/", "", "localhost:5001/tanzu-plugins", nil},
		{"localhost:5001/tanzu-plugins/", "/", "localhost:5001/tanzu-plugins/", nil},

		{"http://localhost:5001/tanzu-plugins/", "/test/path/", "http://localhost:5001/tanzu-plugins/test/path/", nil},
		{"http://localhost:5001/tanzu-plugins", "/test/path/", "http://localhost:5001/tanzu-plugins/test/path/", nil},
		{"http://localhost:5001/tanzu-plugins", "test/path/", "http://localhost:5001/tanzu-plugins/test/path/", nil},
		{"http://localhost:5001/tanzu-plugins/", "test/path/", "http://localhost:5001/tanzu-plugins/test/path/", nil},
		{"http://localhost:5001/tanzu-plugins", "test/path", "http://localhost:5001/tanzu-plugins/test/path", nil},
		{"http://localhost:5001/tanzu-plugins/", "/test/path", "http://localhost:5001/tanzu-plugins/test/path", nil},
		{"http://localhost:5001/tanzu-plugins/", "test/path", "http://localhost:5001/tanzu-plugins/test/path", nil},
		{"http://localhost:5001/tanzu-plugins", "/test/path", "http://localhost:5001/tanzu-plugins/test/path", nil},
		{"http://localhost:5001/tanzu-plugins", "", "http://localhost:5001/tanzu-plugins", nil},
		{"http://localhost:5001/tanzu-plugins/", "", "http://localhost:5001/tanzu-plugins", nil},
		{"http://localhost:5001/tanzu-plugins/", "/", "http://localhost:5001/tanzu-plugins/", nil},

		{"https://localhost:5001/tanzu-plugins/", "/test/path/", "https://localhost:5001/tanzu-plugins/test/path/", nil},
		{"https://localhost:5001/tanzu-plugins", "/test/path/", "https://localhost:5001/tanzu-plugins/test/path/", nil},
		{"https://localhost:5001/tanzu-plugins", "test/path/", "https://localhost:5001/tanzu-plugins/test/path/", nil},
		{"https://localhost:5001/tanzu-plugins/", "test/path/", "https://localhost:5001/tanzu-plugins/test/path/", nil},
		{"https://localhost:5001/tanzu-plugins", "test/path", "https://localhost:5001/tanzu-plugins/test/path", nil},
		{"https://localhost:5001/tanzu-plugins/", "/test/path", "https://localhost:5001/tanzu-plugins/test/path", nil},
		{"https://localhost:5001/tanzu-plugins/", "test/path", "https://localhost:5001/tanzu-plugins/test/path", nil},
		{"https://localhost:5001/tanzu-plugins", "/test/path", "https://localhost:5001/tanzu-plugins/test/path", nil},
		{"https://localhost:5001/tanzu-plugins", "", "https://localhost:5001/tanzu-plugins", nil},
		{"https://localhost:5001/tanzu-plugins/", "", "https://localhost:5001/tanzu-plugins", nil},
		{"https://localhost:5001/tanzu-plugins/", "/", "https://localhost:5001/tanzu-plugins/", nil},

		{"localhost:5001/", "/test/path/", "localhost:5001/test/path/", nil},
		{"localhost:5001", "/test/path/", "localhost:5001/test/path/", nil},
		{"localhost:5001", "test/path/", "localhost:5001/test/path/", nil},
		{"localhost:5001/", "test/path/", "localhost:5001/test/path/", nil},
		{"localhost:5001", "test/path", "localhost:5001/test/path", nil},
		{"localhost:5001/", "/test/path", "localhost:5001/test/path", nil},
		{"localhost:5001/", "test/path", "localhost:5001/test/path", nil},
		{"localhost:5001", "/test/path", "localhost:5001/test/path", nil},
		{"localhost:5001", "", "localhost:5001", nil},
		{"localhost:5001/", "", "localhost:5001/", nil},
		{"localhost:5001/", "/", "localhost:5001/", nil},

		{"http://localhost:5001/", "/test/path/", "http://localhost:5001/test/path/", nil},
		{"http://localhost:5001", "/test/path/", "http://localhost:5001/test/path/", nil},
		{"http://localhost:5001", "test/path/", "http://localhost:5001/test/path/", nil},
		{"http://localhost:5001/", "test/path/", "http://localhost:5001/test/path/", nil},
		{"http://localhost:5001", "test/path", "http://localhost:5001/test/path", nil},
		{"http://localhost:5001/", "/test/path", "http://localhost:5001/test/path", nil},
		{"http://localhost:5001/", "test/path", "http://localhost:5001/test/path", nil},
		{"http://localhost:5001", "/test/path", "http://localhost:5001/test/path", nil},
		{"http://localhost:5001", "", "http://localhost:5001", nil},
		{"http://localhost:5001/", "", "http://localhost:5001/", nil},
		{"http://localhost:5001/", "/", "http://localhost:5001/", nil},

		{"https://localhost:5001/", "/test/path/", "https://localhost:5001/test/path/", nil},
		{"https://localhost:5001", "/test/path/", "https://localhost:5001/test/path/", nil},
		{"https://localhost:5001", "test/path/", "https://localhost:5001/test/path/", nil},
		{"https://localhost:5001/", "test/path/", "https://localhost:5001/test/path/", nil},
		{"https://localhost:5001/", "test/path", "https://localhost:5001/test/path", nil},
		{"https://localhost:5001/", "/test/path", "https://localhost:5001/test/path", nil},
		{"https://localhost:5001/", "test/path", "https://localhost:5001/test/path", nil},
		{"https://localhost:5001", "/test/path", "https://localhost:5001/test/path", nil},
		{"https://localhost:5001", "", "https://localhost:5001", nil},
		{"https://localhost:5001/", "", "https://localhost:5001/", nil},
		{"https://localhost:5001/", "/", "https://localhost:5001/", nil},

		// localhost tests without port

		{"localhost/tanzu-plugins/", "/test/path/", "localhost/tanzu-plugins/test/path/", nil},
		{"localhost/tanzu-plugins", "/test/path/", "localhost/tanzu-plugins/test/path/", nil},
		{"localhost/tanzu-plugins", "test/path/", "localhost/tanzu-plugins/test/path/", nil},
		{"localhost/tanzu-plugins/", "test/path/", "localhost/tanzu-plugins/test/path/", nil},
		{"localhost/tanzu-plugins", "test/path", "localhost/tanzu-plugins/test/path", nil},
		{"localhost/tanzu-plugins/", "/test/path", "localhost/tanzu-plugins/test/path", nil},
		{"localhost/tanzu-plugins/", "test/path", "localhost/tanzu-plugins/test/path", nil},
		{"localhost/tanzu-plugins", "/test/path", "localhost/tanzu-plugins/test/path", nil},
		{"localhost/tanzu-plugins", "", "localhost/tanzu-plugins", nil},
		{"localhost/tanzu-plugins/", "", "localhost/tanzu-plugins", nil},
		{"localhost/tanzu-plugins/", "/", "localhost/tanzu-plugins/", nil},

		{"http://localhost/tanzu-plugins/", "/test/path/", "http://localhost/tanzu-plugins/test/path/", nil},
		{"http://localhost/tanzu-plugins", "/test/path/", "http://localhost/tanzu-plugins/test/path/", nil},
		{"http://localhost/tanzu-plugins", "test/path/", "http://localhost/tanzu-plugins/test/path/", nil},
		{"http://localhost/tanzu-plugins/", "test/path/", "http://localhost/tanzu-plugins/test/path/", nil},
		{"http://localhost/tanzu-plugins", "test/path", "http://localhost/tanzu-plugins/test/path", nil},
		{"http://localhost/tanzu-plugins/", "/test/path", "http://localhost/tanzu-plugins/test/path", nil},
		{"http://localhost/tanzu-plugins/", "test/path", "http://localhost/tanzu-plugins/test/path", nil},
		{"http://localhost/tanzu-plugins", "/test/path", "http://localhost/tanzu-plugins/test/path", nil},
		{"http://localhost/tanzu-plugins", "", "http://localhost/tanzu-plugins", nil},
		{"http://localhost/tanzu-plugins/", "", "http://localhost/tanzu-plugins", nil},
		{"http://localhost/tanzu-plugins/", "/", "http://localhost/tanzu-plugins/", nil},

		{"https://localhost/tanzu-plugins/", "/test/path/", "https://localhost/tanzu-plugins/test/path/", nil},
		{"https://localhost/tanzu-plugins", "/test/path/", "https://localhost/tanzu-plugins/test/path/", nil},
		{"https://localhost/tanzu-plugins", "test/path/", "https://localhost/tanzu-plugins/test/path/", nil},
		{"https://localhost/tanzu-plugins/", "test/path/", "https://localhost/tanzu-plugins/test/path/", nil},
		{"https://localhost/tanzu-plugins", "test/path", "https://localhost/tanzu-plugins/test/path", nil},
		{"https://localhost/tanzu-plugins/", "/test/path", "https://localhost/tanzu-plugins/test/path", nil},
		{"https://localhost/tanzu-plugins/", "test/path", "https://localhost/tanzu-plugins/test/path", nil},
		{"https://localhost/tanzu-plugins", "/test/path", "https://localhost/tanzu-plugins/test/path", nil},
		{"https://localhost/tanzu-plugins", "", "https://localhost/tanzu-plugins", nil},
		{"https://localhost/tanzu-plugins/", "", "https://localhost/tanzu-plugins", nil},
		{"https://localhost/tanzu-plugins/", "/", "https://localhost/tanzu-plugins/", nil},

		{"localhost/", "/test/path/", "localhost/test/path/", nil},
		{"localhost", "/test/path/", "localhost/test/path/", nil},
		{"localhost", "test/path/", "localhost/test/path/", nil},
		{"localhost/", "test/path/", "localhost/test/path/", nil},
		{"localhost", "test/path", "localhost/test/path", nil},
		{"localhost/", "/test/path", "localhost/test/path", nil},
		{"localhost/", "test/path", "localhost/test/path", nil},
		{"localhost", "/test/path", "localhost/test/path", nil},
		{"localhost", "", "localhost", nil},
		{"localhost/", "", "localhost/", nil},
		{"localhost/", "/", "localhost/", nil},

		{"http://localhost/", "/test/path/", "http://localhost/test/path/", nil},
		{"http://localhost", "/test/path/", "http://localhost/test/path/", nil},
		{"http://localhost", "test/path/", "http://localhost/test/path/", nil},
		{"http://localhost/", "test/path/", "http://localhost/test/path/", nil},
		{"http://localhost", "test/path", "http://localhost/test/path", nil},
		{"http://localhost/", "/test/path", "http://localhost/test/path", nil},
		{"http://localhost/", "test/path", "http://localhost/test/path", nil},
		{"http://localhost", "/test/path", "http://localhost/test/path", nil},
		{"http://localhost", "", "http://localhost", nil},
		{"http://localhost/", "", "http://localhost/", nil},
		{"http://localhost/", "/", "http://localhost/", nil},

		{"https://localhost/", "/test/path/", "https://localhost/test/path/", nil},
		{"https://localhost", "/test/path/", "https://localhost/test/path/", nil},
		{"https://localhost", "test/path/", "https://localhost/test/path/", nil},
		{"https://localhost/", "test/path/", "https://localhost/test/path/", nil},
		{"https://localhost/", "test/path", "https://localhost/test/path", nil},
		{"https://localhost/", "/test/path", "https://localhost/test/path", nil},
		{"https://localhost/", "test/path", "https://localhost/test/path", nil},
		{"https://localhost", "/test/path", "https://localhost/test/path", nil},
		{"https://localhost", "", "https://localhost", nil},
		{"https://localhost/", "", "https://localhost/", nil},
		{"https://localhost/", "/", "https://localhost/", nil},

		// full web url without port

		{"www.example.com/tanzu-plugins/", "/test/path/", "www.example.com/tanzu-plugins/test/path/", nil},
		{"www.example.com/tanzu-plugins", "/test/path/", "www.example.com/tanzu-plugins/test/path/", nil},
		{"www.example.com/tanzu-plugins", "test/path/", "www.example.com/tanzu-plugins/test/path/", nil},
		{"www.example.com/tanzu-plugins/", "test/path/", "www.example.com/tanzu-plugins/test/path/", nil},
		{"www.example.com/tanzu-plugins", "test/path", "www.example.com/tanzu-plugins/test/path", nil},
		{"www.example.com/tanzu-plugins/", "/test/path", "www.example.com/tanzu-plugins/test/path", nil},
		{"www.example.com/tanzu-plugins/", "test/path", "www.example.com/tanzu-plugins/test/path", nil},
		{"www.example.com/tanzu-plugins", "/test/path", "www.example.com/tanzu-plugins/test/path", nil},
		{"www.example.com/tanzu-plugins", "", "www.example.com/tanzu-plugins", nil},
		{"www.example.com/tanzu-plugins/", "", "www.example.com/tanzu-plugins", nil},
		{"www.example.com/tanzu-plugins/", "/", "www.example.com/tanzu-plugins/", nil},

		{"http://www.example.com/tanzu-plugins/", "/test/path/", "http://www.example.com/tanzu-plugins/test/path/", nil},
		{"http://www.example.com/tanzu-plugins", "/test/path/", "http://www.example.com/tanzu-plugins/test/path/", nil},
		{"http://www.example.com/tanzu-plugins", "test/path/", "http://www.example.com/tanzu-plugins/test/path/", nil},
		{"http://www.example.com/tanzu-plugins/", "test/path/", "http://www.example.com/tanzu-plugins/test/path/", nil},
		{"http://www.example.com/tanzu-plugins", "test/path", "http://www.example.com/tanzu-plugins/test/path", nil},
		{"http://www.example.com/tanzu-plugins/", "/test/path", "http://www.example.com/tanzu-plugins/test/path", nil},
		{"http://www.example.com/tanzu-plugins/", "test/path", "http://www.example.com/tanzu-plugins/test/path", nil},
		{"http://www.example.com/tanzu-plugins", "/test/path", "http://www.example.com/tanzu-plugins/test/path", nil},
		{"http://www.example.com/tanzu-plugins", "", "http://www.example.com/tanzu-plugins", nil},
		{"http://www.example.com/tanzu-plugins/", "", "http://www.example.com/tanzu-plugins", nil},
		{"http://www.example.com/tanzu-plugins/", "/", "http://www.example.com/tanzu-plugins/", nil},

		{"https://www.example.com/tanzu-plugins/", "/test/path/", "https://www.example.com/tanzu-plugins/test/path/", nil},
		{"https://www.example.com/tanzu-plugins", "/test/path/", "https://www.example.com/tanzu-plugins/test/path/", nil},
		{"https://www.example.com/tanzu-plugins", "test/path/", "https://www.example.com/tanzu-plugins/test/path/", nil},
		{"https://www.example.com/tanzu-plugins/", "test/path/", "https://www.example.com/tanzu-plugins/test/path/", nil},
		{"https://www.example.com/tanzu-plugins", "test/path", "https://www.example.com/tanzu-plugins/test/path", nil},
		{"https://www.example.com/tanzu-plugins/", "/test/path", "https://www.example.com/tanzu-plugins/test/path", nil},
		{"https://www.example.com/tanzu-plugins/", "test/path", "https://www.example.com/tanzu-plugins/test/path", nil},
		{"https://www.example.com/tanzu-plugins", "/test/path", "https://www.example.com/tanzu-plugins/test/path", nil},
		{"https://www.example.com/tanzu-plugins", "", "https://www.example.com/tanzu-plugins", nil},
		{"https://www.example.com/tanzu-plugins/", "", "https://www.example.com/tanzu-plugins", nil},
		{"https://www.example.com/tanzu-plugins/", "/", "https://www.example.com/tanzu-plugins/", nil},

		{"www.example.com/", "/test/path/", "www.example.com/test/path/", nil},
		{"www.example.com", "/test/path/", "www.example.com/test/path/", nil},
		{"www.example.com", "test/path/", "www.example.com/test/path/", nil},
		{"www.example.com/", "test/path/", "www.example.com/test/path/", nil},
		{"www.example.com", "test/path", "www.example.com/test/path", nil},
		{"www.example.com/", "/test/path", "www.example.com/test/path", nil},
		{"www.example.com/", "test/path", "www.example.com/test/path", nil},
		{"www.example.com", "/test/path", "www.example.com/test/path", nil},
		{"www.example.com", "", "www.example.com", nil},
		{"www.example.com/", "", "www.example.com/", nil},
		{"www.example.com/", "/", "www.example.com/", nil},

		{"http://www.example.com/", "/test/path/", "http://www.example.com/test/path/", nil},
		{"http://www.example.com", "/test/path/", "http://www.example.com/test/path/", nil},
		{"http://www.example.com", "test/path/", "http://www.example.com/test/path/", nil},
		{"http://www.example.com/", "test/path/", "http://www.example.com/test/path/", nil},
		{"http://www.example.com", "test/path", "http://www.example.com/test/path", nil},
		{"http://www.example.com/", "/test/path", "http://www.example.com/test/path", nil},
		{"http://www.example.com/", "test/path", "http://www.example.com/test/path", nil},
		{"http://www.example.com", "/test/path", "http://www.example.com/test/path", nil},
		{"http://www.example.com", "", "http://www.example.com", nil},
		{"http://www.example.com/", "", "http://www.example.com/", nil},
		{"http://www.example.com/", "/", "http://www.example.com/", nil},

		{"https://www.example.com/", "/test/path/", "https://www.example.com/test/path/", nil},
		{"https://www.example.com", "/test/path/", "https://www.example.com/test/path/", nil},
		{"https://www.example.com", "test/path/", "https://www.example.com/test/path/", nil},
		{"https://www.example.com/", "test/path/", "https://www.example.com/test/path/", nil},
		{"https://www.example.com/", "test/path", "https://www.example.com/test/path", nil},
		{"https://www.example.com/", "/test/path", "https://www.example.com/test/path", nil},
		{"https://www.example.com/", "test/path", "https://www.example.com/test/path", nil},
		{"https://www.example.com", "/test/path", "https://www.example.com/test/path", nil},
		{"https://www.example.com", "", "https://www.example.com", nil},
		{"https://www.example.com/", "", "https://www.example.com/", nil},
		{"https://www.example.com/", "/", "https://www.example.com/", nil},

		// full web url with port

		{"www.example.com:5001/tanzu-plugins/", "/test/path/", "www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"www.example.com:5001/tanzu-plugins", "/test/path/", "www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"www.example.com:5001/tanzu-plugins", "test/path/", "www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"www.example.com:5001/tanzu-plugins/", "test/path/", "www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"www.example.com:5001/tanzu-plugins", "test/path", "www.example.com:5001/tanzu-plugins/test/path", nil},
		{"www.example.com:5001/tanzu-plugins/", "/test/path", "www.example.com:5001/tanzu-plugins/test/path", nil},
		{"www.example.com:5001/tanzu-plugins/", "test/path", "www.example.com:5001/tanzu-plugins/test/path", nil},
		{"www.example.com:5001/tanzu-plugins", "/test/path", "www.example.com:5001/tanzu-plugins/test/path", nil},
		{"www.example.com:5001/tanzu-plugins", "", "www.example.com:5001/tanzu-plugins", nil},
		{"www.example.com:5001/tanzu-plugins/", "", "www.example.com:5001/tanzu-plugins", nil},
		{"www.example.com:5001/tanzu-plugins/", "/", "www.example.com:5001/tanzu-plugins/", nil},

		{"http://www.example.com:5001/tanzu-plugins/", "/test/path/", "http://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://www.example.com:5001/tanzu-plugins", "/test/path/", "http://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://www.example.com:5001/tanzu-plugins", "test/path/", "http://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://www.example.com:5001/tanzu-plugins/", "test/path/", "http://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://www.example.com:5001/tanzu-plugins", "test/path", "http://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"http://www.example.com:5001/tanzu-plugins/", "/test/path", "http://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"http://www.example.com:5001/tanzu-plugins/", "test/path", "http://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"http://www.example.com:5001/tanzu-plugins", "/test/path", "http://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"http://www.example.com:5001/tanzu-plugins", "", "http://www.example.com:5001/tanzu-plugins", nil},
		{"http://www.example.com:5001/tanzu-plugins/", "", "http://www.example.com:5001/tanzu-plugins", nil},
		{"http://www.example.com:5001/tanzu-plugins/", "/", "http://www.example.com:5001/tanzu-plugins/", nil},

		{"https://www.example.com:5001/tanzu-plugins/", "/test/path/", "https://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://www.example.com:5001/tanzu-plugins", "/test/path/", "https://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://www.example.com:5001/tanzu-plugins", "test/path/", "https://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://www.example.com:5001/tanzu-plugins/", "test/path/", "https://www.example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://www.example.com:5001/tanzu-plugins", "test/path", "https://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"https://www.example.com:5001/tanzu-plugins/", "/test/path", "https://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"https://www.example.com:5001/tanzu-plugins/", "test/path", "https://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"https://www.example.com:5001/tanzu-plugins", "/test/path", "https://www.example.com:5001/tanzu-plugins/test/path", nil},
		{"https://www.example.com:5001/tanzu-plugins", "", "https://www.example.com:5001/tanzu-plugins", nil},
		{"https://www.example.com:5001/tanzu-plugins/", "", "https://www.example.com:5001/tanzu-plugins", nil},
		{"https://www.example.com:5001/tanzu-plugins/", "/", "https://www.example.com:5001/tanzu-plugins/", nil},

		{"www.example.com:5001/", "/test/path/", "www.example.com:5001/test/path/", nil},
		{"www.example.com:5001", "/test/path/", "www.example.com:5001/test/path/", nil},
		{"www.example.com:5001", "test/path/", "www.example.com:5001/test/path/", nil},
		{"www.example.com:5001/", "test/path/", "www.example.com:5001/test/path/", nil},
		{"www.example.com:5001", "test/path", "www.example.com:5001/test/path", nil},
		{"www.example.com:5001/", "/test/path", "www.example.com:5001/test/path", nil},
		{"www.example.com:5001/", "test/path", "www.example.com:5001/test/path", nil},
		{"www.example.com:5001", "/test/path", "www.example.com:5001/test/path", nil},
		{"www.example.com:5001", "", "www.example.com:5001", nil},
		{"www.example.com:5001/", "", "www.example.com:5001/", nil},
		{"www.example.com:5001/", "/", "www.example.com:5001/", nil},

		{"http://www.example.com:5001/", "/test/path/", "http://www.example.com:5001/test/path/", nil},
		{"http://www.example.com:5001", "/test/path/", "http://www.example.com:5001/test/path/", nil},
		{"http://www.example.com:5001", "test/path/", "http://www.example.com:5001/test/path/", nil},
		{"http://www.example.com:5001/", "test/path/", "http://www.example.com:5001/test/path/", nil},
		{"http://www.example.com:5001", "test/path", "http://www.example.com:5001/test/path", nil},
		{"http://www.example.com:5001/", "/test/path", "http://www.example.com:5001/test/path", nil},
		{"http://www.example.com:5001/", "test/path", "http://www.example.com:5001/test/path", nil},
		{"http://www.example.com:5001", "/test/path", "http://www.example.com:5001/test/path", nil},
		{"http://www.example.com:5001", "", "http://www.example.com:5001", nil},
		{"http://www.example.com:5001/", "", "http://www.example.com:5001/", nil},
		{"http://www.example.com:5001/", "/", "http://www.example.com:5001/", nil},

		{"https://www.example.com:5001/", "/test/path/", "https://www.example.com:5001/test/path/", nil},
		{"https://www.example.com:5001", "/test/path/", "https://www.example.com:5001/test/path/", nil},
		{"https://www.example.com:5001", "test/path/", "https://www.example.com:5001/test/path/", nil},
		{"https://www.example.com:5001/", "test/path/", "https://www.example.com:5001/test/path/", nil},
		{"https://www.example.com:5001/", "test/path", "https://www.example.com:5001/test/path", nil},
		{"https://www.example.com:5001/", "/test/path", "https://www.example.com:5001/test/path", nil},
		{"https://www.example.com:5001/", "test/path", "https://www.example.com:5001/test/path", nil},
		{"https://www.example.com:5001", "/test/path", "https://www.example.com:5001/test/path", nil},
		{"https://www.example.com:5001", "", "https://www.example.com:5001", nil},
		{"https://www.example.com:5001/", "", "https://www.example.com:5001/", nil},
		{"https://www.example.com:5001/", "/", "https://www.example.com:5001/", nil},

		// web urls with port

		{"example.com:5001/tanzu-plugins/", "/test/path/", "example.com:5001/tanzu-plugins/test/path/", nil},
		{"example.com:5001/tanzu-plugins", "/test/path/", "example.com:5001/tanzu-plugins/test/path/", nil},
		{"example.com:5001/tanzu-plugins", "test/path/", "example.com:5001/tanzu-plugins/test/path/", nil},
		{"example.com:5001/tanzu-plugins/", "test/path/", "example.com:5001/tanzu-plugins/test/path/", nil},
		{"example.com:5001/tanzu-plugins", "test/path", "example.com:5001/tanzu-plugins/test/path", nil},
		{"example.com:5001/tanzu-plugins/", "/test/path", "example.com:5001/tanzu-plugins/test/path", nil},
		{"example.com:5001/tanzu-plugins/", "test/path", "example.com:5001/tanzu-plugins/test/path", nil},
		{"example.com:5001/tanzu-plugins", "/test/path", "example.com:5001/tanzu-plugins/test/path", nil},
		{"example.com:5001/tanzu-plugins", "", "example.com:5001/tanzu-plugins", nil},
		{"example.com:5001/tanzu-plugins/", "", "example.com:5001/tanzu-plugins", nil},
		{"example.com:5001/tanzu-plugins/", "/", "example.com:5001/tanzu-plugins/", nil},

		{"http://example.com:5001/tanzu-plugins/", "/test/path/", "http://example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://example.com:5001/tanzu-plugins", "/test/path/", "http://example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://example.com:5001/tanzu-plugins", "test/path/", "http://example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://example.com:5001/tanzu-plugins/", "test/path/", "http://example.com:5001/tanzu-plugins/test/path/", nil},
		{"http://example.com:5001/tanzu-plugins", "test/path", "http://example.com:5001/tanzu-plugins/test/path", nil},
		{"http://example.com:5001/tanzu-plugins/", "/test/path", "http://example.com:5001/tanzu-plugins/test/path", nil},
		{"http://example.com:5001/tanzu-plugins/", "test/path", "http://example.com:5001/tanzu-plugins/test/path", nil},
		{"http://example.com:5001/tanzu-plugins", "/test/path", "http://example.com:5001/tanzu-plugins/test/path", nil},
		{"http://example.com:5001/tanzu-plugins", "", "http://example.com:5001/tanzu-plugins", nil},
		{"http://example.com:5001/tanzu-plugins/", "", "http://example.com:5001/tanzu-plugins", nil},
		{"http://example.com:5001/tanzu-plugins/", "/", "http://example.com:5001/tanzu-plugins/", nil},

		{"https://example.com:5001/tanzu-plugins/", "/test/path/", "https://example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://example.com:5001/tanzu-plugins", "/test/path/", "https://example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://example.com:5001/tanzu-plugins", "test/path/", "https://example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://example.com:5001/tanzu-plugins/", "test/path/", "https://example.com:5001/tanzu-plugins/test/path/", nil},
		{"https://example.com:5001/tanzu-plugins", "test/path", "https://example.com:5001/tanzu-plugins/test/path", nil},
		{"https://example.com:5001/tanzu-plugins/", "/test/path", "https://example.com:5001/tanzu-plugins/test/path", nil},
		{"https://example.com:5001/tanzu-plugins/", "test/path", "https://example.com:5001/tanzu-plugins/test/path", nil},
		{"https://example.com:5001/tanzu-plugins", "/test/path", "https://example.com:5001/tanzu-plugins/test/path", nil},
		{"https://example.com:5001/tanzu-plugins", "", "https://example.com:5001/tanzu-plugins", nil},
		{"https://example.com:5001/tanzu-plugins/", "", "https://example.com:5001/tanzu-plugins", nil},
		{"https://example.com:5001/tanzu-plugins/", "/", "https://example.com:5001/tanzu-plugins/", nil},

		{"example.com:5001/", "/test/path/", "example.com:5001/test/path/", nil},
		{"example.com:5001", "/test/path/", "example.com:5001/test/path/", nil},
		{"example.com:5001", "test/path/", "example.com:5001/test/path/", nil},
		{"example.com:5001/", "test/path/", "example.com:5001/test/path/", nil},
		{"example.com:5001", "test/path", "example.com:5001/test/path", nil},
		{"example.com:5001/", "/test/path", "example.com:5001/test/path", nil},
		{"example.com:5001/", "test/path", "example.com:5001/test/path", nil},
		{"example.com:5001", "/test/path", "example.com:5001/test/path", nil},
		{"example.com:5001", "", "example.com:5001", nil},
		{"example.com:5001/", "", "example.com:5001/", nil},
		{"example.com:5001/", "/", "example.com:5001/", nil},

		{"http://example.com:5001/", "/test/path/", "http://example.com:5001/test/path/", nil},
		{"http://example.com:5001", "/test/path/", "http://example.com:5001/test/path/", nil},
		{"http://example.com:5001", "test/path/", "http://example.com:5001/test/path/", nil},
		{"http://example.com:5001/", "test/path/", "http://example.com:5001/test/path/", nil},
		{"http://example.com:5001", "test/path", "http://example.com:5001/test/path", nil},
		{"http://example.com:5001/", "/test/path", "http://example.com:5001/test/path", nil},
		{"http://example.com:5001/", "test/path", "http://example.com:5001/test/path", nil},
		{"http://example.com:5001", "/test/path", "http://example.com:5001/test/path", nil},
		{"http://example.com:5001", "", "http://example.com:5001", nil},
		{"http://example.com:5001/", "", "http://example.com:5001/", nil},
		{"http://example.com:5001/", "/", "http://example.com:5001/", nil},

		{"https://example.com:5001/", "/test/path/", "https://example.com:5001/test/path/", nil},
		{"https://example.com:5001", "/test/path/", "https://example.com:5001/test/path/", nil},
		{"https://example.com:5001", "test/path/", "https://example.com:5001/test/path/", nil},
		{"https://example.com:5001/", "test/path/", "https://example.com:5001/test/path/", nil},
		{"https://example.com:5001/", "test/path", "https://example.com:5001/test/path", nil},
		{"https://example.com:5001/", "/test/path", "https://example.com:5001/test/path", nil},
		{"https://example.com:5001/", "test/path", "https://example.com:5001/test/path", nil},
		{"https://example.com:5001", "/test/path", "https://example.com:5001/test/path", nil},
		{"https://example.com:5001", "", "https://example.com:5001", nil},
		{"https://example.com:5001/", "", "https://example.com:5001/", nil},
		{"https://example.com:5001/", "/", "https://example.com:5001/", nil},

		// web urls without port

		{"example.com/tanzu-plugins/", "/test/path/", "example.com/tanzu-plugins/test/path/", nil},
		{"example.com/tanzu-plugins", "/test/path/", "example.com/tanzu-plugins/test/path/", nil},
		{"example.com/tanzu-plugins", "test/path/", "example.com/tanzu-plugins/test/path/", nil},
		{"example.com/tanzu-plugins/", "test/path/", "example.com/tanzu-plugins/test/path/", nil},
		{"example.com/tanzu-plugins", "test/path", "example.com/tanzu-plugins/test/path", nil},
		{"example.com/tanzu-plugins/", "/test/path", "example.com/tanzu-plugins/test/path", nil},
		{"example.com/tanzu-plugins/", "test/path", "example.com/tanzu-plugins/test/path", nil},
		{"example.com/tanzu-plugins", "/test/path", "example.com/tanzu-plugins/test/path", nil},
		{"example.com/tanzu-plugins", "", "example.com/tanzu-plugins", nil},
		{"example.com/tanzu-plugins/", "", "example.com/tanzu-plugins", nil},
		{"example.com/tanzu-plugins/", "/", "example.com/tanzu-plugins/", nil},

		{"http://example.com/tanzu-plugins/", "/test/path/", "http://example.com/tanzu-plugins/test/path/", nil},
		{"http://example.com/tanzu-plugins", "/test/path/", "http://example.com/tanzu-plugins/test/path/", nil},
		{"http://example.com/tanzu-plugins", "test/path/", "http://example.com/tanzu-plugins/test/path/", nil},
		{"http://example.com/tanzu-plugins/", "test/path/", "http://example.com/tanzu-plugins/test/path/", nil},
		{"http://example.com/tanzu-plugins", "test/path", "http://example.com/tanzu-plugins/test/path", nil},
		{"http://example.com/tanzu-plugins/", "/test/path", "http://example.com/tanzu-plugins/test/path", nil},
		{"http://example.com/tanzu-plugins/", "test/path", "http://example.com/tanzu-plugins/test/path", nil},
		{"http://example.com/tanzu-plugins", "/test/path", "http://example.com/tanzu-plugins/test/path", nil},
		{"http://example.com/tanzu-plugins", "", "http://example.com/tanzu-plugins", nil},
		{"http://example.com/tanzu-plugins/", "", "http://example.com/tanzu-plugins", nil},
		{"http://example.com/tanzu-plugins/", "/", "http://example.com/tanzu-plugins/", nil},

		{"https://example.com/tanzu-plugins/", "/test/path/", "https://example.com/tanzu-plugins/test/path/", nil},
		{"https://example.com/tanzu-plugins", "/test/path/", "https://example.com/tanzu-plugins/test/path/", nil},
		{"https://example.com/tanzu-plugins", "test/path/", "https://example.com/tanzu-plugins/test/path/", nil},
		{"https://example.com/tanzu-plugins/", "test/path/", "https://example.com/tanzu-plugins/test/path/", nil},
		{"https://example.com/tanzu-plugins", "test/path", "https://example.com/tanzu-plugins/test/path", nil},
		{"https://example.com/tanzu-plugins/", "/test/path", "https://example.com/tanzu-plugins/test/path", nil},
		{"https://example.com/tanzu-plugins/", "test/path", "https://example.com/tanzu-plugins/test/path", nil},
		{"https://example.com/tanzu-plugins", "/test/path", "https://example.com/tanzu-plugins/test/path", nil},
		{"https://example.com/tanzu-plugins", "", "https://example.com/tanzu-plugins", nil},
		{"https://example.com/tanzu-plugins/", "", "https://example.com/tanzu-plugins", nil},
		{"https://example.com/tanzu-plugins/", "/", "https://example.com/tanzu-plugins/", nil},

		{"example.com/", "/test/path/", "example.com/test/path/", nil},
		{"example.com", "/test/path/", "example.com/test/path/", nil},
		{"example.com", "test/path/", "example.com/test/path/", nil},
		{"example.com/", "test/path/", "example.com/test/path/", nil},
		{"example.com", "test/path", "example.com/test/path", nil},
		{"example.com/", "/test/path", "example.com/test/path", nil},
		{"example.com/", "test/path", "example.com/test/path", nil},
		{"example.com", "/test/path", "example.com/test/path", nil},
		{"example.com", "", "example.com", nil},
		{"example.com/", "", "example.com/", nil},
		{"example.com/", "/", "example.com/", nil},

		{"http://example.com/", "/test/path/", "http://example.com/test/path/", nil},
		{"http://example.com", "/test/path/", "http://example.com/test/path/", nil},
		{"http://example.com", "test/path/", "http://example.com/test/path/", nil},
		{"http://example.com/", "test/path/", "http://example.com/test/path/", nil},
		{"http://example.com", "test/path", "http://example.com/test/path", nil},
		{"http://example.com/", "/test/path", "http://example.com/test/path", nil},
		{"http://example.com/", "test/path", "http://example.com/test/path", nil},
		{"http://example.com", "/test/path", "http://example.com/test/path", nil},
		{"http://example.com", "", "http://example.com", nil},
		{"http://example.com/", "", "http://example.com/", nil},
		{"http://example.com/", "/", "http://example.com/", nil},

		{"https://example.com/", "/test/path/", "https://example.com/test/path/", nil},
		{"https://example.com", "/test/path/", "https://example.com/test/path/", nil},
		{"https://example.com", "test/path/", "https://example.com/test/path/", nil},
		{"https://example.com/", "test/path/", "https://example.com/test/path/", nil},
		{"https://example.com/", "test/path", "https://example.com/test/path", nil},
		{"https://example.com/", "/test/path", "https://example.com/test/path", nil},
		{"https://example.com/", "test/path", "https://example.com/test/path", nil},
		{"https://example.com", "/test/path", "https://example.com/test/path", nil},
		{"https://example.com", "", "https://example.com", nil},
		{"https://example.com/", "", "https://example.com/", nil},
		{"https://example.com/", "/", "https://example.com/", nil},
	}

	for _, tt := range testCases {
		testName := fmt.Sprintf("%v,%v", tt.baseURL, tt.relativeURL)
		t.Run(testName, func(t *testing.T) {
			ans, err := JoinURL(tt.baseURL, tt.relativeURL)
			if tt.error != nil {
				assert.Equal(t, tt.error.Error(), err.Error())
			}
			assert.Equal(t, tt.expected, ans)
		})
	}
}
