linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/AlecAivazis/survey/v2
          - github.com/Masterminds/semver
          - github.com/adrg/xdg
          - github.com/cppforlife/go-cli-ui
          - github.com/fatih/color
          - github.com/gobwas/glob
          - github.com/golang-jwt/jwt
          - github.com/google/gnostic
          - github.com/google/go-containerregistry
          - github.com/google/uuid
          - github.com/gorilla/mux
          - github.com/imdario/mergo
          - github.com/juju/fslock
          - github.com/k14s/kbld
          - github.com/lithammer/dedent
          - github.com/logrusorgru/aurora
          - github.com/novln/docker-parser
          - github.com/onsi/ginkgo/v2
          - github.com/onsi/gomega
          - github.com/otiai10/copy
          - github.com/pkg/errors
          - github.com/sigstore/cosign/v2
          - github.com/sigstore/sigstore
          - github.com/spf13/afero
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/stretchr/testify
          - github.com/tj/assert
          - github.com/verybluebot/tarinator-go
          - github.com/vmware-tanzu/carvel-imgpkg
          - github.com/vmware-tanzu/carvel-ytt
          - github.com/vmware-tanzu/tanzu-cli
          - github.com/vmware-tanzu/tanzu-cli/test/e2e/framework
          - github.com/vmware-tanzu/tanzu-framework/capabilities/client
          - github.com/vmware-tanzu/tanzu-plugin-runtime
          - go.pinniped.dev
          - go.uber.org/multierr
          - google.golang.org/grpc
          - golang.org/x/oauth2
          - golang.org/x/sync/errgroup
          - golang.org/x/mod/semver
          - gopkg.in/yaml.v2
          - gopkg.in/yaml.v3
          - k8s.io/api
          - k8s.io/apimachinery
          - k8s.io/client-go
          - modernc.org/sqlite
          - sigs.k8s.io/controller-runtime
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: not allowed
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goheader:
    values:
      const:
        COMPANY: 'VMware, Inc.'
        LICENSE: Apache-2.0
      regexp:
        YEAR: 20\d*-*\d*
    template: |-
      Copyright {{ YEAR }} {{ COMPANY }} All Rights Reserved.
      SPDX-License-Identifier: {{ LICENSE }}
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/vmware-tanzu
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  whitespace:
    multi-func: true
linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - bodyclose
    - noctx
    - rowserrcheck
  # don't enable:
  # - asciicheck
  # - exhaustive
  # - gochecknoinits
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - lll
  # - nestif
  # - prealloc
  # - testpackage
  # - scopelint
  # - wsl

issues:
  exclude:
    - declaration of "(err|ctx)" shadows declaration at
    - 'unnamedResult: consider giving a name to these results'
    - >-
      (Expect directory permissions to be 0750 or less|Expect (WriteFile|file)
      permissions to be 0600 or less)
  exclude-rules:
    - linters:
        - gosec
      text: 'G602:'
    - path: _test\.go
      linters:
        - dupl
        - gocritic
        - funlen
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: 'unnecessaryDefer:'
    - linters:
        - revive
      text: that stutters
    - path: zz_.*\.go
      linters:
        - revive
      text: it will be inferred from
    - path: (.+)_test.go
      linters:
        - staticcheck
      text: 'SA1019:'
  include:
    - EXC0011
  max-same-issues: 0
  max-issues-per-linter: 0
run:
  skip-dirs:
    - fakes/
  timeout: 15m
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.46.0 # use the fixed version to not introduce new linters unexpectedly
