apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cliplugin.cli.tanzu.vmware.com.0.0.0
spec:
  refName: cliplugin.cli.tanzu.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - cli.tanzu.vmware.com_cliplugins.yaml
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cliplugin.cli.tanzu.vmware.com
spec:
  displayName: cliplugin
  longDescription: cliplugin.cli.tanzu.vmware.com
  shortDescription: cliplugin.cli.tanzu.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: cliplugin
spec:
  packageRef:
    refName: cliplugin.cli.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: cliplugin-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
