// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/vmware-tanzu/tanzu-cli/pkg/cli"
	"github.com/vmware-tanzu/tanzu-cli/pkg/plugincmdtree"
)

type CommandTreeCache struct {
	ConstructAndAddTreeStub        func(*cli.PluginInfo) error
	constructAndAddTreeMutex       sync.RWMutex
	constructAndAddTreeArgsForCall []struct {
		arg1 *cli.PluginInfo
	}
	constructAndAddTreeReturns struct {
		result1 error
	}
	constructAndAddTreeReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteTreeStub        func(*cli.PluginInfo) error
	deleteTreeMutex       sync.RWMutex
	deleteTreeArgsForCall []struct {
		arg1 *cli.PluginInfo
	}
	deleteTreeReturns struct {
		result1 error
	}
	deleteTreeReturnsOnCall map[int]struct {
		result1 error
	}
	GetTreeStub        func(*cli.PluginInfo) (*plugincmdtree.CommandNode, error)
	getTreeMutex       sync.RWMutex
	getTreeArgsForCall []struct {
		arg1 *cli.PluginInfo
	}
	getTreeReturns struct {
		result1 *plugincmdtree.CommandNode
		result2 error
	}
	getTreeReturnsOnCall map[int]struct {
		result1 *plugincmdtree.CommandNode
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CommandTreeCache) ConstructAndAddTree(arg1 *cli.PluginInfo) error {
	fake.constructAndAddTreeMutex.Lock()
	ret, specificReturn := fake.constructAndAddTreeReturnsOnCall[len(fake.constructAndAddTreeArgsForCall)]
	fake.constructAndAddTreeArgsForCall = append(fake.constructAndAddTreeArgsForCall, struct {
		arg1 *cli.PluginInfo
	}{arg1})
	stub := fake.ConstructAndAddTreeStub
	fakeReturns := fake.constructAndAddTreeReturns
	fake.recordInvocation("ConstructAndAddTree", []interface{}{arg1})
	fake.constructAndAddTreeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommandTreeCache) ConstructAndAddTreeCallCount() int {
	fake.constructAndAddTreeMutex.RLock()
	defer fake.constructAndAddTreeMutex.RUnlock()
	return len(fake.constructAndAddTreeArgsForCall)
}

func (fake *CommandTreeCache) ConstructAndAddTreeCalls(stub func(*cli.PluginInfo) error) {
	fake.constructAndAddTreeMutex.Lock()
	defer fake.constructAndAddTreeMutex.Unlock()
	fake.ConstructAndAddTreeStub = stub
}

func (fake *CommandTreeCache) ConstructAndAddTreeArgsForCall(i int) *cli.PluginInfo {
	fake.constructAndAddTreeMutex.RLock()
	defer fake.constructAndAddTreeMutex.RUnlock()
	argsForCall := fake.constructAndAddTreeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CommandTreeCache) ConstructAndAddTreeReturns(result1 error) {
	fake.constructAndAddTreeMutex.Lock()
	defer fake.constructAndAddTreeMutex.Unlock()
	fake.ConstructAndAddTreeStub = nil
	fake.constructAndAddTreeReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommandTreeCache) ConstructAndAddTreeReturnsOnCall(i int, result1 error) {
	fake.constructAndAddTreeMutex.Lock()
	defer fake.constructAndAddTreeMutex.Unlock()
	fake.ConstructAndAddTreeStub = nil
	if fake.constructAndAddTreeReturnsOnCall == nil {
		fake.constructAndAddTreeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.constructAndAddTreeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommandTreeCache) DeleteTree(arg1 *cli.PluginInfo) error {
	fake.deleteTreeMutex.Lock()
	ret, specificReturn := fake.deleteTreeReturnsOnCall[len(fake.deleteTreeArgsForCall)]
	fake.deleteTreeArgsForCall = append(fake.deleteTreeArgsForCall, struct {
		arg1 *cli.PluginInfo
	}{arg1})
	stub := fake.DeleteTreeStub
	fakeReturns := fake.deleteTreeReturns
	fake.recordInvocation("DeleteTree", []interface{}{arg1})
	fake.deleteTreeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommandTreeCache) DeleteTreeCallCount() int {
	fake.deleteTreeMutex.RLock()
	defer fake.deleteTreeMutex.RUnlock()
	return len(fake.deleteTreeArgsForCall)
}

func (fake *CommandTreeCache) DeleteTreeCalls(stub func(*cli.PluginInfo) error) {
	fake.deleteTreeMutex.Lock()
	defer fake.deleteTreeMutex.Unlock()
	fake.DeleteTreeStub = stub
}

func (fake *CommandTreeCache) DeleteTreeArgsForCall(i int) *cli.PluginInfo {
	fake.deleteTreeMutex.RLock()
	defer fake.deleteTreeMutex.RUnlock()
	argsForCall := fake.deleteTreeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CommandTreeCache) DeleteTreeReturns(result1 error) {
	fake.deleteTreeMutex.Lock()
	defer fake.deleteTreeMutex.Unlock()
	fake.DeleteTreeStub = nil
	fake.deleteTreeReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommandTreeCache) DeleteTreeReturnsOnCall(i int, result1 error) {
	fake.deleteTreeMutex.Lock()
	defer fake.deleteTreeMutex.Unlock()
	fake.DeleteTreeStub = nil
	if fake.deleteTreeReturnsOnCall == nil {
		fake.deleteTreeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteTreeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommandTreeCache) GetTree(arg1 *cli.PluginInfo) (*plugincmdtree.CommandNode, error) {
	fake.getTreeMutex.Lock()
	ret, specificReturn := fake.getTreeReturnsOnCall[len(fake.getTreeArgsForCall)]
	fake.getTreeArgsForCall = append(fake.getTreeArgsForCall, struct {
		arg1 *cli.PluginInfo
	}{arg1})
	stub := fake.GetTreeStub
	fakeReturns := fake.getTreeReturns
	fake.recordInvocation("GetTree", []interface{}{arg1})
	fake.getTreeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CommandTreeCache) GetTreeCallCount() int {
	fake.getTreeMutex.RLock()
	defer fake.getTreeMutex.RUnlock()
	return len(fake.getTreeArgsForCall)
}

func (fake *CommandTreeCache) GetTreeCalls(stub func(*cli.PluginInfo) (*plugincmdtree.CommandNode, error)) {
	fake.getTreeMutex.Lock()
	defer fake.getTreeMutex.Unlock()
	fake.GetTreeStub = stub
}

func (fake *CommandTreeCache) GetTreeArgsForCall(i int) *cli.PluginInfo {
	fake.getTreeMutex.RLock()
	defer fake.getTreeMutex.RUnlock()
	argsForCall := fake.getTreeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CommandTreeCache) GetTreeReturns(result1 *plugincmdtree.CommandNode, result2 error) {
	fake.getTreeMutex.Lock()
	defer fake.getTreeMutex.Unlock()
	fake.GetTreeStub = nil
	fake.getTreeReturns = struct {
		result1 *plugincmdtree.CommandNode
		result2 error
	}{result1, result2}
}

func (fake *CommandTreeCache) GetTreeReturnsOnCall(i int, result1 *plugincmdtree.CommandNode, result2 error) {
	fake.getTreeMutex.Lock()
	defer fake.getTreeMutex.Unlock()
	fake.GetTreeStub = nil
	if fake.getTreeReturnsOnCall == nil {
		fake.getTreeReturnsOnCall = make(map[int]struct {
			result1 *plugincmdtree.CommandNode
			result2 error
		})
	}
	fake.getTreeReturnsOnCall[i] = struct {
		result1 *plugincmdtree.CommandNode
		result2 error
	}{result1, result2}
}

func (fake *CommandTreeCache) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.constructAndAddTreeMutex.RLock()
	defer fake.constructAndAddTreeMutex.RUnlock()
	fake.deleteTreeMutex.RLock()
	defer fake.deleteTreeMutex.RUnlock()
	fake.getTreeMutex.RLock()
	defer fake.getTreeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CommandTreeCache) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ plugincmdtree.Cache = new(CommandTreeCache)
