apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cliplugins.cli.tanzu.vmware.com.0.0.0
  namespace: tanzu-system
spec:
  refName: cliplugins.cli.tanzu.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - carvel\
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: cliplugins.cli.tanzu.vmware.com
  namespace: tanzu-system
spec:
  displayName: cliplugins.cli
  longDescription: "CLIPlugins package provides the CLIPlugin CRD"
  shortDescription: "CLIPlugin management"
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  name: cliplugins
  namespace: tanzu-system
spec:
  packageRef:
    refName: cliplugins.cli.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: cliplugins-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
