apiVersion: v1
kind: Config
current-context: baz-context
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://baz.org:4443
    name: baz-cluster
contexts:
  - context:
      cluster: baz-cluster
      namespace: default
      user: baz-user
    name: baz-context
users:
  - name: baz-user
    user:
      token: baz-user-token
