name: Main

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, test* ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Config credentials
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache linting
      uses: actions/cache@v3
      with:
        path: ${{ runner.temp }}/lint_cache
        key: ${{ runner.os }}-lint-cache-2

    - name: Test
      run: |
        make all

    - name: Run make verify
      run: |
        make verify
